# Generated by Django 5.1.4 on 2025-01-04 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=24)),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User_Calendar',
            fields=[
                ('eventID', models.IntegerField(primary_key=True, serialize=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palendar_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Group_Calendar',
            fields=[
                ('groupID', models.IntegerField(primary_key=True, serialize=False)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palendar_app.user_calendar')),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palendar_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=16)),
                ('event_desc', models.CharField(max_length=128)),
                ('event_date', models.DateTimeField()),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palendar_app.user_calendar')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palendar_app.users')),
            ],
        ),
    ]
