# Generated by Django 5.1.4 on 2025-01-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
