# Generated by Django 5.1.4 on 2025-01-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palendar_app', '0003_alter_users_email_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
