# Generated by Django 5.1.4 on 2025-01-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palendar_app', '0005_remove_group_calendar_eventid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcalendar',
            name='eventID',
        ),
    ]
