# Generated by Django 5.1.4 on 2025-01-17 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palendar_app', '0006_remove_groupcalendar_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcalendar',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='palendar_app.users'),
        ),
    ]
