# Generated by Django 5.1.4 on 2025-01-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palendar_app', '0007_alter_groupcalendar_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcalendar',
            name='members',
        ),
        migrations.AddField(
            model_name='groupcalendar',
            name='members',
            field=models.ManyToManyField(null=True, related_name='groups', to='palendar_app.users'),
        ),
    ]
